2021-12-02 17:53:02,592 INFO    MainThread:1688921 [wandb_setup.py:_flush():69] setting env: {}
2021-12-02 17:53:02,592 INFO    MainThread:1688921 [wandb_setup.py:_flush():69] setting login settings: {}
2021-12-02 17:53:02,592 INFO    MainThread:1688921 [wandb_init.py:_log_setup():357] Logging user logs to /home/lts5-ts/Documents/ahmed/bmai_ahmed/wandb/run-20211202_175302-3rce7g8j/logs/debug.log
2021-12-02 17:53:02,593 INFO    MainThread:1688921 [wandb_init.py:_log_setup():358] Logging internal logs to /home/lts5-ts/Documents/ahmed/bmai_ahmed/wandb/run-20211202_175302-3rce7g8j/logs/debug-internal.log
2021-12-02 17:53:02,593 INFO    MainThread:1688921 [wandb_init.py:init():390] calling init triggers
2021-12-02 17:53:02,593 INFO    MainThread:1688921 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-12-02 17:53:02,593 INFO    MainThread:1688921 [wandb_init.py:init():435] starting backend
2021-12-02 17:53:02,593 INFO    MainThread:1688921 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-02 17:53:02,612 INFO    MainThread:1688921 [backend.py:ensure_launched():135] starting backend process...
2021-12-02 17:53:02,618 INFO    MainThread:1688921 [backend.py:ensure_launched():139] started backend process with pid: 1688930
2021-12-02 17:53:02,619 INFO    MainThread:1688921 [wandb_init.py:init():440] backend started and connected
2021-12-02 17:53:02,619 INFO    MainThread:1688921 [wandb_init.py:init():499] updated telemetry
2021-12-02 17:53:02,620 INFO    MainThread:1688921 [wandb_init.py:init():522] communicating current version
2021-12-02 17:53:03,073 INFO    MainThread:1688921 [wandb_init.py:init():527] got version response upgrade_message: "wandb version 0.12.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-02 17:53:03,073 INFO    MainThread:1688921 [wandb_init.py:init():535] communicating run to backend with 30 second timeout
2021-12-02 17:53:03,274 INFO    MainThread:1688921 [wandb_init.py:init():562] starting run threads in backend
2021-12-02 17:53:04,527 INFO    MainThread:1688921 [wandb_run.py:_console_start():1651] atexit reg
2021-12-02 17:53:04,527 INFO    MainThread:1688921 [wandb_run.py:_redirect():1525] redirect: SettingsConsole.REDIRECT
2021-12-02 17:53:04,528 INFO    MainThread:1688921 [wandb_run.py:_redirect():1530] Redirecting console.
2021-12-02 17:53:04,529 INFO    MainThread:1688921 [wandb_run.py:_redirect():1586] Redirects installed.
2021-12-02 17:53:04,529 INFO    MainThread:1688921 [wandb_init.py:init():587] run started, returning control to user process
2021-12-02 17:53:04,611 INFO    MainThread:1688921 [wandb_run.py:_atexit_cleanup():1621] got exitcode: 1
2021-12-02 17:53:04,611 INFO    MainThread:1688921 [wandb_run.py:_restore():1593] restore
2021-12-02 17:53:07,042 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 1089
}

2021-12-02 17:53:07,351 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 1089
}

2021-12-02 17:53:08,306 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 6646
}

2021-12-02 17:53:08,408 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 8165
}

2021-12-02 17:53:08,513 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1089
  total_bytes: 8165
}

2021-12-02 17:53:08,616 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}

2021-12-02 17:53:08,719 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}

2021-12-02 17:53:08,822 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}

2021-12-02 17:53:08,925 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}

2021-12-02 17:53:09,027 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}

2021-12-02 17:53:09,233 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}

2021-12-02 17:53:09,659 INFO    MainThread:1688921 [wandb_run.py:_wait_for_finish():1746] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8165
  total_bytes: 8165
}
local_info {
}

2021-12-02 17:53:10,737 INFO    MainThread:1688921 [wandb_run.py:_append_files():2009] logging synced files
