Traceback (most recent call last):
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 56, in <module>
    main(args)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 46, in main
    trainer = BmaiTrainer(model, dataset, AGE=args.AGE, SEXE=args.SEXE, batch_size=args.batch_size, lr = args.lr, num_workers=args.num_workers)
TypeError: __init__() got an unexpected keyword argument 'lr'