
About to train for 10 epochs
epoch: 0/9, batch 0/16, loss: 1648.4987635613977
epoch: 0/9, batch 10/16, loss: 286.9477741622925
for epoch 0 , average loss is 836.602038224401
About to test
Average test loss is 131.34886612057684
Traceback (most recent call last):
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 53, in <module>
    main(args)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 44, in main
    results,mean_training_loss = trainer.train(args.epochs)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/trainer_bmai_2.py", line 195, in train
    mean_height_rel_error, mean_weight_rel_error, avg_test_loss = self.test(epoch)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/trainer_bmai_2.py", line 273, in test
    mean_height_rel_error,mean_weight_rel_error = calculate_mean_absolute_error_results(y_true,y_predictions)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/trainer_bmai_2.py", line 288, in calculate_mean_absolute_error_results
    df['predicted_height'] = predictions[:,0]
NameError: name 'predictions' is not defined